name: pawang_hujan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.6
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.1.3
  go_router: ^6.2.0
  google_fonts: ^3.0.1
  flutter_svg: ^2.0.5
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  mocktail: ^0.3.0
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/weather/
  uses-material-design: true
